Add support to validate UIElement does not exist
treatwell/twuitests pull request #21
Opened 2020-09-09 18:07 UTC by sclancy

2020-09-10 15:22 UTC, davdroman requested changes

2020-09-10 15:22 UTC, davdroman commented on TWUITests/Helpers/XCUIElement+Extensions.swift
> +            ? "Element \(identifier) should exist  after delay"
Double whitespace `exist  after`

2020-09-14 07:42 UTC, lokatorius commented on TWUITests/Helpers/XCUIElement+Extensions.swift
> +            : NSPredicate(format: "exists == false")
I'm not sure that this works as intended. So if UI element will appear after 1 second and we want to check if element doesn't not appear -> we will get false positive:

1. screen appears in a loading state
2. we check some UILabel with this method and it give result that label does not exist (because the way `XCTNSPredicateExpectation` works).
3. Label appears after 1 sec but it doesn't matter because we got result that label is not present on the screen.

So we still need to wait till UI elements are drawn on the screen. And in this case we can simply use `exists` method for assertion.

2020-10-02 11:21 UTC, sclancy commented
No longer needed.

2020-10-02 11:21 UTC, closed without merging